import { Scenario } from './types.js';

// Sample scenarios from the plan document
export const SEED_SCENARIOS: Scenario[] = [
  // Church Scenarios
  {
    id: 's-01',
    title: 'Chapel Choir',
    description: 'Sing a hymn together inside a church',
    mediaType: 'video',
    category: 'church',
    difficulty: 'medium',
  },
  {
    id: 's-02',
    title: 'Steeple Selfie',
    description: 'Group photo with a church steeple in the background',
    mediaType: 'photo',
    category: 'church',
    difficulty: 'easy',
  },
  {
    id: 's-03',
    title: 'Painting Copy',
    description: 'Pose as subjects in a painting with the actual painting in background',
    mediaType: 'photo',
    category: 'church',
    difficulty: 'medium',
  },
  {
    id: 's-04',
    title: 'Pew Pose',
    description: 'Team sitting reverently in chapel pews',
    mediaType: 'photo',
    category: 'church',
    difficulty: 'easy',
  },

  // General Scenarios
  {
    id: 's-05',
    title: 'Abbey Road',
    description: 'Walk across a crosswalk like the Beatles',
    mediaType: 'photo',
    category: 'general',
    difficulty: 'easy',
  },
  {
    id: 's-06',
    title: 'Fountain Swimmers',
    description: 'Make swimming and diving motions in front of a fountain',
    mediaType: 'video',
    category: 'general',
    difficulty: 'easy',
  },
  {
    id: 's-07',
    title: 'Tree Huggers',
    description: 'Group hug a tree',
    mediaType: 'photo',
    category: 'general',
    difficulty: 'easy',
  },
  {
    id: 's-08',
    title: 'Viral Recreation',
    description: 'Recreate a famous viral or meme video',
    mediaType: 'video',
    category: 'general',
    difficulty: 'medium',
  },
  {
    id: 's-09',
    title: 'Stranger Workout',
    description: 'Do at least 5 pushups together with a stranger',
    mediaType: 'video',
    category: 'general',
    difficulty: 'hard',
  },
  {
    id: 's-10',
    title: 'Movie Moment',
    description: 'Reenact a short scene from a well known movie',
    mediaType: 'video',
    category: 'general',
    difficulty: 'medium',
  },
  {
    id: 's-11',
    title: 'Nature Documentary',
    description: 'Film something ordinary and narrate it like wildlife',
    mediaType: 'video',
    category: 'general',
    difficulty: 'medium',
  },
  {
    id: 's-12',
    title: 'Duck Walk',
    description: 'Waddle in a line like ducks',
    mediaType: 'video',
    category: 'general',
    difficulty: 'easy',
  },
  {
    id: 's-13',
    title: 'Human Pyramid',
    description: 'Form a human pyramid with your team',
    mediaType: 'photo',
    category: 'general',
    difficulty: 'easy',
  },
  {
    id: 's-24',
    title: 'How Rude',
    description: 'Take a drink of soda an burp.',
    mediaType: 'video',
    category: 'general',
    difficulty: 'hard',
  },
  {
    id: 's-25',
    title: 'Synchronized Acrobatics',
    description: 'Do cartwheels or at least try to.  (whole group)',
    mediaType: 'video',
    category: 'general',
    difficulty: 'easy',
  },
  {
    id: 's-26',
    title: 'Look Ma, No Hands',
    description: 'A team member eating food with no hands', 
    mediaType: 'video',
    category: 'general',
    difficulty: 'medium',
  },
  {
    id: 's-27',
    title: 'History Lesson',
    description: 'Recreate a famous historical photo (eg. Iwo Jima, VJ Day, etc.)', 
    mediaType: 'photo',
    category: 'general',
    difficulty: 'easy',
  },
  {
    id: 's-28',
    title: 'Draw The Foul',
    description: 'Have a team member fall to the ground pretending to be dramatically injured (aka Lebroning)',
    mediaType: 'video',
    category: 'general',
    difficulty: 'easy',
  },
  {
    id: 's-29',
    title: 'Dramatic Slow-Mo',
    description: 'Film a dramatic slow motion video of something ordinary (eg. dropping a pen, walking through a door, etc.)',
    mediaType: 'video',
    category: 'general',
    difficulty: 'medium',
  },
  {
    id: 's-30',
    title: 'Human Mirror',
    description: 'Two team members facing each other and mirroring each other\'s movements',
    mediaType: 'video',
    category: 'general',
    difficulty: 'medium',
  },
  {
    id: 's-31',
    title: 'Sock Puppets',
    description: 'Make sock puppets on your hands and have them interact with each other',
    mediaType: 'video',
    category: 'general',
    difficulty: 'easy',
  },
  {
    id: 's-32',
    title: 'Shoe Balance 1.0',
    description: 'Balance on one foot with a shoe on your head (unique person for each Shoe Balance)',
    mediaType: 'photo',
    category: 'general',
    difficulty: 'easy',
  },
  {
    id: 's-33',
    title: 'Shoe Balance 2.0',
    description: 'Balance on one foot with a shoe on your head while holding a drink in your hand (unique person for each Shoe Balance)',
    mediaType: 'photo',
    category: 'general',
    difficulty: 'medium',
  },
  {
    id: 's-34',
    title: 'Shoe Balance 3.0',
    description: 'Balance on one foot with a shoe on your head while holding a drink in your hand and singing a song (unique person for each Shoe Balance)',
    mediaType: 'video',
    category: 'general',
    difficulty: 'hard',
  },

  // Location-Based Scenarios
  {
    id: 's-14',
    title: 'Gas Station Hero',
    description: 'Pump gas for a stranger at a gas station',
    mediaType: 'video',
    category: 'location',
    difficulty: 'hard',
  },
  {
    id: 's-15',
    title: 'Frozen Performance',
    description: 'Sing "Once there was a snowman" in the frozen foods section of a grocery store',
    mediaType: 'video',
    category: 'location',
    difficulty: 'medium',
  },
  {
    id: 's-16',
    title: 'YMCA at the Y',
    description: 'Sing and dance to YMCA in front of a gym',
    mediaType: 'video',
    category: 'location',
    difficulty: 'medium',
  },
  {
    id: 's-17',
    title: 'Civic Duty',
    description: 'Give a short speech in front of a government building (eg. library, post office)',
    mediaType: 'video',
    category: 'location',
    difficulty: 'medium',
  },
  {
    id: 's-18',
    title: 'Playground Pro',
    description: 'Swing from monkey bars',
    mediaType: 'photo',
    category: 'location',
    difficulty: 'easy',
  },
  {
    id: 's-19',
    title: 'Play Ball',
    description: 'Sing the last line of the National Anthem at a baseball diamond',
    mediaType: 'video',
    category: 'location',
    difficulty: 'medium',
  },
  {
    id: 's-20',
    title: 'Wrong Restaurant',
    description: "Go to McDonald's and try to order a Whopper",
    mediaType: 'video',
    category: 'location',
    difficulty: 'hard',
  },
  {
    id: 's-21',
    title: 'Cart Racers',
    description: 'Two team members being pushed in a shopping cart',
    mediaType: 'video',
    category: 'location',
    difficulty: 'medium',
  },
  {
    id: 's-22',
    title: 'Photo Finish',
    description: 'Race on a track with a dramatic finish',
    mediaType: 'photo',
    category: 'location',
    difficulty: 'medium',
  },
  {
    id: 's-23',
    title: 'Fitness Fanatic',
    description: 'Do jumping jacks in front of a gym',
    mediaType: 'video',
    category: 'location',
    difficulty: 'easy',
  },
];
