import { Scenario } from './types.js';

// Sample scenarios from the plan document
export const SEED_SCENARIOS: Scenario[] = [
  // Location-Based Scenarios
  {
    id: 'loc-01',
    title: 'Gas Station Hero',
    description: 'Pump gas for a stranger at a gas station',
    mediaType: 'video',
    category: 'location',
    difficulty: 'hard',
  },
  {
    id: 'loc-02',
    title: 'Frozen Performance',
    description: 'Sing "Once there was a snowman" in the frozen foods section',
    mediaType: 'video',
    category: 'location',
    difficulty: 'medium',
  },
  {
    id: 'loc-03',
    title: 'Abbey Road',
    description: 'Walk across a crosswalk like the Beatles',
    mediaType: 'video',
    category: 'location',
    difficulty: 'easy',
  },
  {
    id: 'loc-04',
    title: 'YMCA at the Y',
    description: 'Sing and dance to YMCA in front of a gym',
    mediaType: 'video',
    category: 'location',
    difficulty: 'medium',
  },
  {
    id: 'loc-05',
    title: 'Civic Duty',
    description: 'Give a short speech in front of a government building',
    mediaType: 'video',
    category: 'location',
    difficulty: 'medium',
  },
  {
    id: 'loc-06',
    title: 'Fountain Swimmers',
    description: 'Make swimming and diving motions in front of a fountain',
    mediaType: 'video',
    category: 'location',
    difficulty: 'easy',
  },
  {
    id: 'loc-07',
    title: 'Playground Pro',
    description: 'Swing from monkey bars',
    mediaType: 'photo',
    category: 'location',
    difficulty: 'easy',
  },
  {
    id: 'loc-08',
    title: 'Tree Huggers',
    description: 'Group hug a tree',
    mediaType: 'photo',
    category: 'location',
    difficulty: 'easy',
  },
  {
    id: 'loc-09',
    title: 'Play Ball',
    description: 'Sing the last line of the National Anthem at a baseball diamond',
    mediaType: 'video',
    category: 'location',
    difficulty: 'medium',
  },
  {
    id: 'loc-10',
    title: 'Wrong Restaurant',
    description: "Go to McDonald's and try to order a Whopper",
    mediaType: 'video',
    category: 'location',
    difficulty: 'hard',
  },

  // General Scenarios
  {
    id: 'gen-01',
    title: 'Viral Recreation',
    description: 'Recreate a famous viral or meme video',
    mediaType: 'video',
    category: 'general',
    difficulty: 'medium',
  },
  {
    id: 'gen-02',
    title: 'Stranger Workout',
    description: 'Do at least 5 pushups together with a stranger',
    mediaType: 'video',
    category: 'general',
    difficulty: 'hard',
  },
  {
    id: 'gen-03',
    title: 'Movie Moment',
    description: 'Reenact a short scene from your favorite movie',
    mediaType: 'video',
    category: 'general',
    difficulty: 'medium',
  },
  {
    id: 'gen-04',
    title: 'Nature Documentary',
    description: 'Film something ordinary and narrate it like wildlife',
    mediaType: 'video',
    category: 'general',
    difficulty: 'easy',
  },
  {
    id: 'gen-05',
    title: 'Duck Walk',
    description: 'Waddle in a line like ducks',
    mediaType: 'video',
    category: 'general',
    difficulty: 'easy',
  },
  {
    id: 'gen-06',
    title: 'Human Pyramid',
    description: 'Form a human pyramid at a mall',
    mediaType: 'photo',
    category: 'general',
    difficulty: 'easy',
  },
  {
    id: 'gen-07',
    title: 'Cart Racers',
    description: 'Two team members being pushed in a shopping cart',
    mediaType: 'video',
    category: 'general',
    difficulty: 'medium',
  },
  {
    id: 'gen-08',
    title: 'Photo Finish',
    description: 'Race on a track with a dramatic finish',
    mediaType: 'photo',
    category: 'general',
    difficulty: 'medium',
  },
  {
    id: 'gen-09',
    title: 'Fitness Fanatic',
    description: 'Do jumping jacks in front of a gym',
    mediaType: 'video',
    category: 'general',
    difficulty: 'easy',
  },

  // Church Scenarios
  {
    id: 'church-01',
    title: 'Chapel Choir',
    description: 'Sing a hymn together inside a church',
    mediaType: 'video',
    category: 'church',
    difficulty: 'medium',
  },
  {
    id: 'church-02',
    title: 'Steeple Selfie',
    description: 'Group photo with a church steeple in the background',
    mediaType: 'photo',
    category: 'church',
    difficulty: 'easy',
  },
  {
    id: 'church-03',
    title: 'Painting Copy',
    description: 'Pose as subjects in a painting with the actual painting in background',
    mediaType: 'photo',
    category: 'church',
    difficulty: 'medium',
  },
  {
    id: 'church-04',
    title: 'Pew Pose',
    description: 'Team sitting reverently in church pews',
    mediaType: 'photo',
    category: 'church',
    difficulty: 'easy',
  },
];
